-- Generates the body of supabase/base_schema.sql from the live catalog.
-- Every name is schema-qualified because search_path is pg_catalog only.
SET search_path = pg_catalog;

WITH
tbl AS (
  SELECT c.oid, c.relname
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind IN ('r','p')
),
sec(ord, title) AS (VALUES
  (1,'1. Extensions'),(2,'2. Enum types'),(3,'3. Tables'),
  (4,'4. Primary keys and unique constraints'),(5,'5. Check constraints'),
  (6,'6. Foreign keys'),(7,'7. Indexes'),(8,'8. Functions'),(9,'9. Triggers'),
  (10,'10. Row level security'),(11,'11. Storage buckets and policies')
),
body AS (
  -- 1. extensions (Supabase ships these in schema "extensions"; IF NOT EXISTS
  --    makes the block a no-op on a normal project where they already exist)
  SELECT 1 AS ord, e.extname AS k, 0 AS sub,
         format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname) AS line
  FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace
  WHERE e.extname NOT IN ('plpgsql','supabase_vault')

  -- 2. enums
  UNION ALL
  SELECT 2, t.typname, 0,
         format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
                (SELECT string_agg(quote_literal(enumlabel), ', ' ORDER BY enumsortorder)
                 FROM pg_enum WHERE enumtypid = t.oid))
  FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public' AND t.typtype = 'e'

  -- 3. tables
  UNION ALL
  SELECT 3, tbl.relname, 0,
         format(E'CREATE TABLE public.%I (\n%s\n);\n', tbl.relname,
           (SELECT string_agg(
                     format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
                       CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                          WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END,
                       CASE WHEN a.attgenerated = 's'
                            THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                            WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
                            ELSE '' END,
                       CASE WHEN a.attnotnull AND a.attidentity = '' THEN ' NOT NULL' ELSE '' END),
                     E',\n' ORDER BY a.attnum)
            FROM pg_attribute a
            LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE a.attrelid = tbl.oid AND a.attnum > 0 AND NOT a.attisdropped))
  FROM tbl

  -- 4-6. constraints (NOT NULL lives on the column above)
  UNION ALL
  SELECT CASE co.contype WHEN 'c' THEN 5 WHEN 'f' THEN 6 ELSE 4 END,
         tbl.relname || '.' || co.conname,
         CASE co.contype WHEN 'p' THEN 0 ELSE 1 END,
         format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', tbl.relname, co.conname,
                pg_get_constraintdef(co.oid))
  FROM pg_constraint co JOIN tbl ON tbl.oid = co.conrelid
  WHERE co.contype IN ('p','u','c','f','x')

  -- 7. indexes that do not back a constraint
  UNION ALL
  SELECT 7, tbl.relname || '.' || ic.relname, 0, pg_get_indexdef(i.indexrelid) || ';'
  FROM pg_index i JOIN tbl ON tbl.oid = i.indrelid
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE NOT EXISTS (SELECT 1 FROM pg_constraint co WHERE co.conindid = i.indexrelid AND co.conrelid = i.indrelid)

  -- 8. functions, plus an explicit ACL wherever it differs from the default
  UNION ALL
  SELECT 8, p.proname, 0, rtrim(pg_get_functiondef(p.oid), E'\n') || ';'
       || CASE WHEN p.proacl IS NOT NULL AND NOT (p.proacl::text LIKE '%anon=X%')
               THEN E'\n\n' || format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated;', p.oid::regprocedure)
                 || (SELECT string_agg(E'\n' || format('GRANT EXECUTE ON FUNCTION %s TO %I;', p.oid::regprocedure,
                                                      pg_get_userbyid(x.grantee)), '' ORDER BY pg_get_userbyid(x.grantee))
                     FROM aclexplode(p.proacl) x
                     WHERE x.grantee <> 0 AND pg_get_userbyid(x.grantee) NOT IN ('postgres'))
               ELSE '' END
       || E'\n'
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')

  -- 9. triggers on public tables and the one on auth.users
  UNION ALL
  SELECT 9, c.relname || '.' || tg.tgname, 0, pg_get_triggerdef(tg.oid) || ';'
  FROM pg_trigger tg JOIN pg_class c ON c.oid = tg.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE NOT tg.tgisinternal
    AND (n.nspname = 'public' OR (n.nspname = 'auth' AND c.relname = 'users'))

  -- 10. RLS switches, then policies
  UNION ALL
  SELECT 10, c.relname, 0,
         format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname)
         || CASE WHEN c.relforcerowsecurity THEN format(E'\nALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', c.relname) ELSE '' END
  FROM pg_class c JOIN tbl ON tbl.oid = c.oid WHERE c.relrowsecurity
  UNION ALL
  SELECT 10, p.tablename || '.' || p.policyname, 1,
         format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
                p.policyname, p.tablename, p.permissive, p.cmd,
                (SELECT string_agg(CASE WHEN r = 'public' THEN 'public' ELSE quote_ident(r) END, ', ' ORDER BY r)
                 FROM unnest(p.roles) r),
                CASE WHEN p.qual IS NOT NULL THEN E'\n  USING (' || p.qual || ')' ELSE '' END,
                CASE WHEN p.with_check IS NOT NULL THEN E'\n  WITH CHECK (' || p.with_check || ')' ELSE '' END)
  FROM pg_policies p WHERE p.schemaname = 'public'

  -- 11. storage buckets + storage.objects policies
  UNION ALL
  SELECT 11, b.id, 0,
         format('INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES (%L, %L, %s, %s, %s) ON CONFLICT (id) DO NOTHING;',
                b.id, b.name, CASE WHEN b.public THEN 'true' ELSE 'false' END,
                coalesce(b.file_size_limit::text, 'NULL'),
                coalesce(quote_literal(b.allowed_mime_types::text) || '::text[]', 'NULL'))
  FROM storage.buckets b
  UNION ALL
  SELECT 11, 'zz.' || p.policyname, 1,
         format('CREATE POLICY %I ON storage.objects AS %s FOR %s TO %s%s%s;',
                p.policyname, p.permissive, p.cmd,
                (SELECT string_agg(quote_ident(r), ', ' ORDER BY r) FROM unnest(p.roles) r),
                CASE WHEN p.qual IS NOT NULL THEN E'\n  USING (' || p.qual || ')' ELSE '' END,
                CASE WHEN p.with_check IS NOT NULL THEN E'\n  WITH CHECK (' || p.with_check || ')' ELSE '' END)
  FROM pg_policies p WHERE p.schemaname = 'storage' AND p.tablename = 'objects'
)
SELECT line FROM (
  SELECT s.ord, '' AS k, -1 AS sub,
         E'\n-- -----------------------------------------------------------------------------\n-- '
         || s.title || E'\n-- -----------------------------------------------------------------------------\n' AS line
  FROM sec s
  UNION ALL
  SELECT ord, k, sub, line FROM body
) x
ORDER BY ord, sub, k;
